# Generated by Django 3.1.7 on 2021-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0004_auto_20210416_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal',
            name='category',
            field=models.IntegerField(choices=[(0, 'Telegrams'), (1, 'Post office at war'), (2, 'post office equipments'), (3, 'post office savings bank'), (4, 'postmarking machines'), (5, 'DateStamps'), (6, 'Stamp Dispensing Machines'), (7, 'Temporary Post Offices'), (8, 'Other post office history'), (9, 'NZ P & T IN WW1'), (10, 'FRANKING MACHINES'), (11, 'New Zealand'), (12, 'Non New Zealand')], default=0),
        ),
        migrations.DeleteModel(
            name='PostalCategory',
        ),
    ]
