# Generated by Django 3.1.7 on 2021-04-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0008_auto_20210416_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='postal',
            options={'ordering': ['-datePosted'], 'verbose_name_plural': 'Postals'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
