# Generated by Django 3.1.7 on 2021-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0009_auto_20210416_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Add Links'},
        ),
        migrations.AlterModelOptions(
            name='philatelist',
            options={'verbose_name_plural': 'Make new account'},
        ),
    ]
