# Generated by Django 3.1.7 on 2021-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0013_auto_20210416_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
