# Generated by Django 3.1.7 on 2021-04-17 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0014_auto_20210416_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal',
            name='postContent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
