# Generated by Django 3.1.7 on 2021-04-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0016_auto_20210417_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postal',
            name='postImages',
        ),
        migrations.AddField(
            model_name='postalimages',
            name='postImages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_stamp.postal'),
        ),
    ]
