# Generated by Django 3.1.7 on 2021-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0017_auto_20210417_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postalimages',
            name='postalImages',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
