# Generated by Django 3.1.7 on 2021-04-18 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0019_auto_20210417_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativeTitle', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='images/')),
                ('postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_stamp.postal')),
            ],
        ),
    ]
