# Generated by Django 3.1.7 on 2021-04-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0020_postalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostalImage',
        ),
    ]
