# Generated by Django 3.1.7 on 2021-04-19 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0022_postalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='history',
            new_name='aboutUsTitle',
        ),
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
        migrations.AlterField(
            model_name='history',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
