# Generated by Django 3.1.7 on 2021-04-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0023_auto_20210419_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='slug',
            field=models.SlugField(help_text='Please use the title of your post as the slug.', max_length=200, null=True),
        ),
    ]
