# Generated by Django 3.1.7 on 2021-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0024_history_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-datePosted',), 'verbose_name_plural': 'About Us'},
        ),
    ]
