# Generated by Django 3.1.7 on 2021-04-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0026_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
