# Generated by Django 3.1.7 on 2021-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0028_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(help_text='Please use the subject of your post as the slug.', max_length=200, null=True, verbose_name='subject'),
        ),
    ]
