# Generated by Django 3.1.7 on 2021-04-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0031_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
