# Generated by Django 3.1.7 on 2021-04-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0032_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalimage',
            name='slug',
            field=models.SlugField(help_text='Please use the title of your post as the slug.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
