# Generated by Django 3.1.7 on 2021-04-30 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0035_auto_20210430_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='philatelyAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.TextField(verbose_name='URL Link'),
        ),
        migrations.AlterField(
            model_name='links',
            name='urlTitle',
            field=models.CharField(max_length=150, unique=True, verbose_name='Title of URL'),
        ),
    ]
