# Generated by Django 3.1.7 on 2021-04-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0036_auto_20210430_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='aboutUsTitle',
            field=models.CharField(default='About Us', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='slug',
            field=models.SlugField(help_text='Please use the title of your post as the slug.', max_length=200, null=True, verbose_name='Code'),
        ),
    ]
