# Generated by Django 3.1.7 on 2021-04-30 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0037_auto_20210430_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='aboutUsTitle',
            field=models.CharField(default='About Us', max_length=150, unique=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='history',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='history',
            name='philatelyAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
