# Generated by Django 3.1.7 on 2021-04-30 04:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0039_auto_20210430_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal',
            name='category',
            field=models.IntegerField(choices=[(0, 'Telegrams'), (1, 'Post office at war'), (2, 'post office equipments'), (3, 'post office savings bank'), (4, 'postmarking machines'), (5, 'DateStamps'), (6, 'Stamp Dispensing Machines'), (7, 'Temporary Post Offices'), (8, 'Other post office history'), (9, 'NZ P & T IN WW1'), (10, 'FRANKING MACHINES'), (11, 'New Zealand'), (12, 'Non New Zealand')], default=0, help_text='the page where you would put the post', verbose_name='Page Category'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Upload Image'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='philatelyAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='postContent',
            field=ckeditor.fields.RichTextField(verbose_name='Postal Content'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='postTitle',
            field=models.CharField(max_length=150, verbose_name='Title of post'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='slug',
            field=models.SlugField(help_text='Please use the title of your post as the code.', max_length=200, unique=True, verbose_name='Unique Code'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='sub_category',
            field=models.ForeignKey(help_text='Sub Category it is part of, if none, create one.', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_stamp.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='postalimage',
            name='postal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_stamp.postal', verbose_name='What post would you put your image'),
        ),
        migrations.AlterField(
            model_name='postalimage',
            name='postalImage',
            field=models.FileField(upload_to='images/', verbose_name='Upload Image'),
        ),
        migrations.AlterField(
            model_name='postalimage',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Title of Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(max_length=150, verbose_name='Sub Category'),
        ),
    ]
