# Generated by Django 3.1.7 on 2021-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0040_auto_20210430_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Key Code'),
        ),
    ]
