# Generated by Django 3.1.7 on 2021-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0043_auto_20210430_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='datePosted',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='links',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postal',
            name='datePosted',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Posted'),
        ),
    ]
