# Generated by Django 3.1.7 on 2021-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0047_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0),
        ),
    ]
