# Generated by Django 3.1.7 on 2021-05-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0049_auto_20210503_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='philatelyAuthor',
        ),
    ]
