# Generated by Django 3.1.7 on 2021-05-28 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_stamp', '0050_remove_history_philatelyauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='aboutUsTitle',
            field=models.CharField(default='About Us', max_length=150, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='history',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True, verbose_name='Date Posted'),
        ),
    ]
